// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ArchitecturePanel } from './ArchitecturePanel';
import { analysisFile, DEFAULT_ANALYSIS, ArchitectureFormatError, type ArchitectureDocument } from '../../architecture/model';
const { read, list } = vi.hoisted(() => ({ read: vi.fn(), list: vi.fn() }));
vi.mock('../../architecture/api', () => ({ readArchitecture: read, listArchitectures: list }));
vi.mock('./ArchitectureDiagram', () => ({ ArchitectureDiagram: () => <div>Diagram</div> }));
const document: ArchitectureDocument = {
  version: 1, generatedAt: '2026-10-09T09:00:00Z', summary: 'A terminal application',
  perspectives: [{ id: 'overview', title: 'Overview', summary: 'Modules', nodes: [
    { id: 'server', title: 'Server', summary: 'Backend', files: [{ path: 'src/server/entry.ts', line: 12 }] },
    { id: 'routes', parentId: 'server', title: 'Routes', summary: 'Request dispatch', files: [{ path: 'src/server/routes/filesystem.ts', line: 50 }] },
  ], edges: [] }, { id: 'data', title: 'Data flow', summary: 'Data', nodes: [
    { id: 'input', title: 'Input', summary: 'Terminal input', files: [] },
  ], edges: [] }],
};
const props = () => ({ rootPath: '/project', active: true, onInsertPrompt: vi.fn().mockResolvedValue(true), onOpenFile: vi.fn() });
beforeEach(() => { sessionStorage.clear(); read.mockReset(); list.mockReset(); list.mockResolvedValue([]); });
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); });
describe('native architecture browsing', () => {
  it('opens the only saved scoped map on a fresh client and honors a later explicit overview selection', async () => {
    const analysis = { ...DEFAULT_ANALYSIS, kind: 'feature' as const, target: 'Upload' };
    const file = analysisFile(analysis);
    list.mockResolvedValue([file]);
    read.mockResolvedValueOnce(null).mockResolvedValueOnce({ ...document, analysis, summary: 'Upload map' }).mockResolvedValue(null);
    render(<ArchitecturePanel {...props()} />);
    await screen.findByText('Upload map');
    expect((screen.getByRole('combobox', { name: 'Saved analyses' }) as HTMLSelectElement).value).toBe(file);
    fireEvent.change(screen.getByRole('combobox', { name: 'Saved analyses' }), { target: { value: '.termdock/architecture.json' } });
    await screen.findByText("Understand this project's architecture");
    expect((screen.getByRole('combobox', { name: 'Saved analyses' }) as HTMLSelectElement).value).toBe('.termdock/architecture.json');
    expect(read).toHaveBeenCalledTimes(3);
  });
  it('keeps verbose analysis notes collapsed and shows readable module cards without a graph on narrow panels', async () => {
    const summary = 'Analyzed sources: src/server/entry.ts. Scope limitations and verification notes. '.repeat(20);
    read.mockResolvedValue({ ...document, summary });
    render(<ArchitecturePanel {...props()} />);
    await screen.findByRole('button', { name: 'Server' });
    expect(screen.queryByText('Diagram')).toBeNull();
    expect(screen.getByRole('button', { name: 'Module details' }).getAttribute('aria-pressed')).toBe('true');
    const notes = screen.getByText(summary.trim()).closest('details')!;
    expect(notes.open).toBe(false);
    fireEvent.click(screen.getByRole('button', { name: 'Server' }));
    expect(screen.getByRole('region', { name: 'Server' }).textContent).toContain('Backend');
    fireEvent.click(screen.getByRole('button', { name: 'Relationship diagram' }));
    expect(screen.getByText('Diagram')).toBeTruthy();
    expect(notes.open).toBe(false);
  });
  it('explains folded connections and navigates to the linked module directly', async () => {
    const map = structuredClone(document);
    map.perspectives[0].nodes.push({ id: 'ui', title: 'UI', summary: 'User interface', files: [] });
    map.perspectives[0].edges = [{ from: 'ui', to: 'routes', label: 'Requests' }, { from: 'routes', to: 'ui', label: 'Responses' }];
    read.mockResolvedValue(map);
    render(<ArchitecturePanel {...props()} />);
    await screen.findByRole('button', { name: 'Server' });
    fireEvent.click(screen.getByRole('button', { name: 'Server' }));
    expect(screen.getByRole('button', { name: 'To: UI · Responses' })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'From: UI · Requests' }));
    expect(screen.getByRole('region', { name: 'UI' }).textContent).toContain('User interface');
    fireEvent.click(screen.getByRole('button', { name: 'Close module details' }));
    expect(screen.queryByRole('region', { name: 'UI' })).toBeNull();
    expect(screen.getByRole('button', { name: 'UI' })).toBeTruthy();
  });
  it('keeps module details open when Escape belongs to an IME composition', async () => {
    read.mockResolvedValue(document);
    render(<ArchitecturePanel {...props()} />);
    await screen.findByRole('button', { name: 'Server' });
    fireEvent.click(screen.getByRole('button', { name: 'Server' }));
    fireEvent.keyDown(globalThis.document.activeElement!, { key: 'Escape', isComposing: true });
    expect(screen.getByRole('region', { name: 'Server' })).toBeTruthy();
    fireEvent.keyDown(globalThis.document.activeElement!, { key: 'Escape' });
    expect(screen.queryByRole('region', { name: 'Server' })).toBeNull();
  });
  it('remembers the selected map per project and rejects unsafe saved selections', async () => {
    const analysis = { ...DEFAULT_ANALYSIS, kind: 'feature' as const, target: 'Upload' };
    const file = analysisFile(analysis);
    list.mockResolvedValue([file]);
    read.mockResolvedValue({ ...document, analysis });
    const input = props();
    const view = render(<ArchitecturePanel {...input} />);
    await screen.findByText('A terminal application');
    fireEvent.change(screen.getByRole('combobox', { name: 'Saved analyses' }), { target: { value: file } });
    await waitFor(() => expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), file));
    view.unmount();
    const reopened = render(<ArchitecturePanel {...input} />);
    await waitFor(() => expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), file));
    expect((screen.getByRole('combobox', { name: 'Saved analyses' }) as HTMLSelectElement).value).toBe(file);
    sessionStorage.setItem('termdock.architecture.selection:/another', '../../secret.json');
    reopened.rerender(<ArchitecturePanel {...input} rootPath="/another" />);
    await waitFor(() => expect(read).toHaveBeenLastCalledWith('/another', expect.any(AbortSignal), '.termdock/architecture.json'));
  });
  it('closes update settings on Escape, restores focus and does not insert a prompt', async () => {
    read.mockResolvedValue(document);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText('A terminal application');
    const trigger = screen.getByRole('button', { name: 'Update' });
    trigger.focus(); fireEvent.click(trigger);
    const form = screen.getByRole('heading', { name: 'Update current analysis' }).closest('form')!;
    expect(form.contains(globalThis.document.activeElement)).toBe(true);
    fireEvent.keyDown(form, { key: 'Escape', isComposing: true });
    expect(screen.getByRole('heading', { name: 'Update current analysis' })).toBeTruthy();
    fireEvent.keyDown(form, { key: 'Escape' });
    expect(screen.queryByRole('heading', { name: 'Update current analysis' })).toBeNull();
    await waitFor(() => expect(globalThis.document.activeElement).toBe(trigger));
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
  });
  it('owns focus while preparing, ignores hidden panels and resumes when reopened', async () => {
    read.mockResolvedValue(document);
    const input = props();
    const view = render(<><input aria-label="Terminal stand-in" /><ArchitecturePanel {...input} /></>);
    await screen.findByText('A terminal application');
    fireEvent.click(screen.getByRole('button', { name: 'Update' }));
    const form = screen.getByRole('heading', { name: 'Update current analysis' }).closest('form')!;
    const background = screen.getByRole('textbox', { name: 'Terminal stand-in' });
    background.focus();
    expect(form.contains(globalThis.document.activeElement)).toBe(true);
    view.rerender(<><input aria-label="Terminal stand-in" /><ArchitecturePanel {...input} active={false} /></>);
    background.focus();
    expect(globalThis.document.activeElement).toBe(background);
    view.rerender(<><input aria-label="Terminal stand-in" /><ArchitecturePanel {...input} /></>);
    background.focus();
    expect(form.contains(globalThis.document.activeElement)).toBe(true);
    fireEvent.keyDown(globalThis.document.activeElement!, { key: 'Escape' });
    expect(screen.queryByRole('heading', { name: 'Update current analysis' })).toBeNull();
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
  });
  it('handles unavailable clipboard without inserting or changing the selected map', async () => {
    read.mockResolvedValue(null);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText("Understand this project's architecture");
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    vi.stubGlobal('navigator', {});
    fireEvent.click(screen.getByRole('button', { name: 'Copy prompt' }));
    await screen.findByText(/Copy failed/);
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
    expect(read).toHaveBeenCalledTimes(1);
  });
  it('creates a feature map without requiring or overwriting a project overview', async () => {
    read.mockResolvedValue(null);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText("Understand this project's architecture");
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    fireEvent.change(screen.getByRole('combobox', { name: 'Analysis scope' }), { target: { value: 'feature' } });
    expect((screen.getByRole('button', { name: 'Insert prompt' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(screen.getByRole('textbox', { name: 'Feature to understand' }), { target: { value: 'File upload' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledWith(expect.stringContaining('Analyze ONLY the requested feature'), expect.any(HTMLFormElement)));
    await screen.findByText(/Review the current input/);
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('.termdock/architectures/feature-File-upload-');
    fireEvent.click(screen.getByRole('button', { name: 'Close analysis settings' }));
    await screen.findByText(/This analysis has not been saved yet/);
    expect((screen.getByRole('combobox', { name: 'Saved analyses' }) as HTMLSelectElement).value).toContain('/feature-');
  });
  it('validates module paths and permits multiple project-relative paths', async () => {
    read.mockResolvedValue(null);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText("Understand this project's architecture");
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    fireEvent.change(screen.getByRole('combobox', { name: 'Analysis scope' }), { target: { value: 'module' } });
    const field = screen.getByRole('textbox', { name: 'Module paths (one per line)' });
    fireEvent.change(field, { target: { value: '../secret' } });
    expect(screen.getByRole('alert')).toBeTruthy();
    expect((screen.getByRole('button', { name: 'Insert prompt' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(field, { target: { value: 'src/server\npackages/auth' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledOnce());
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('src/server');
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('packages/auth');
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('Analyze ONLY the specified module paths');
  });
  it('keeps the selected map and prepared feature unchanged until insertion succeeds', async () => {
    read.mockResolvedValue(null);
    const input = props();
    let finish!: (accepted: boolean) => void;
    input.onInsertPrompt.mockReturnValueOnce(new Promise<boolean>(resolve => { finish = resolve; })).mockResolvedValueOnce(true);
    render(<ArchitecturePanel {...input} />);
    await screen.findByText("Understand this project's architecture");
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    fireEvent.change(screen.getByRole('combobox', { name: 'Analysis scope' }), { target: { value: 'feature' } });
    fireEvent.change(screen.getByRole('textbox', { name: 'Feature to understand' }), { target: { value: 'Upload retries' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledOnce());
    expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), '.termdock/architecture.json');
    expect(read).toHaveBeenCalledTimes(1);
    await act(async () => finish(false));
    expect(screen.getByRole('status').textContent).toContain('Could not add the prompt');
    expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), '.termdock/architecture.json');
    expect(sessionStorage.getItem('termdock.architecture.selection:/project')).toBeNull();
    expect((screen.getByRole('textbox', { name: 'Feature to understand' }) as HTMLInputElement).value).toBe('Upload retries');
    expect(read).toHaveBeenCalledTimes(1);
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await screen.findByText(/Review the current input/);
    const featureFile = analysisFile({ ...DEFAULT_ANALYSIS, kind: 'feature', target: 'Upload retries' });
    fireEvent.click(screen.getByRole('button', { name: 'Close analysis settings' }));
    expect((screen.getByRole('combobox', { name: 'Saved analyses' }) as HTMLSelectElement).value).toBe(featureFile);
    expect(sessionStorage.getItem('termdock.architecture.selection:/project')).toBe(featureFile);
    await waitFor(() => expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), featureFile));
  });
  it('prepares a module analysis from verified sources without changing the current map on cancel', async () => {
    read.mockResolvedValue(document);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText('A terminal application');
    fireEvent.click(screen.getByRole('button', { name: 'Server' }));
    fireEvent.click(screen.getByRole('button', { name: 'Analyze this module in detail' }));
    expect((screen.getByRole('textbox', { name: 'Module paths (one per line)' }) as HTMLTextAreaElement).value).toBe('src/server/entry.ts');
    fireEvent.click(screen.getByRole('button', { name: 'Close analysis settings' }));
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
    expect(screen.getByText('A terminal application')).toBeTruthy();
  });
  it('switches independent maps, cancels stale reads and updates only the selected scope', async () => {
    const analysis = { ...DEFAULT_ANALYSIS, kind: 'feature' as const, target: 'Upload' };
    const file = analysisFile(analysis);
    list.mockResolvedValue([file]);
    read.mockResolvedValueOnce(document);
    const input = props();
    const scoped = { ...document, summary: 'Upload flow', analysis };
    render(<ArchitecturePanel {...input} />);
    await screen.findByText('A terminal application');
    let finishOld!: (doc: ArchitectureDocument) => void;
    read.mockReturnValueOnce(new Promise(resolve => { finishOld = resolve; })).mockResolvedValue(scoped);
    fireEvent.click(screen.getByRole('button', { name: 'Refresh architecture' }));
    const oldSignal = read.mock.calls[1][1] as AbortSignal;
    fireEvent.change(screen.getByRole('combobox', { name: 'Saved analyses' }), { target: { value: file } });
    await screen.findByText('Upload flow');
    expect(oldSignal.aborted).toBe(true);
    await act(async () => { finishOld({ ...document, summary: 'Late project result' }); });
    expect(screen.queryByText('Late project result')).toBeNull();
    expect(read).toHaveBeenLastCalledWith('/project', expect.any(AbortSignal), file);
    fireEvent.click(screen.getByRole('button', { name: 'Update' }));
    expect((screen.getByRole('combobox', { name: 'Analysis scope' }) as HTMLSelectElement).disabled).toBe(true);
    expect((screen.getByRole('textbox', { name: 'Feature to understand' }) as HTMLInputElement).readOnly).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledOnce());
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain(JSON.stringify(file));
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('leave all other saved maps unchanged');
  });
  it('keeps the current map usable when library listing fails and recovers on refresh', async () => {
    read.mockResolvedValue(document);
    list.mockRejectedValueOnce(new Error('Disconnected')).mockResolvedValue([]);
    render(<ArchitecturePanel {...props()} />);
    await screen.findByText('A terminal application');
    expect(screen.getByRole('alert').textContent).toContain('Could not list analyses');
    fireEvent.click(screen.getByRole('button', { name: 'Refresh architecture' }));
    await waitFor(() => expect(screen.queryByRole('alert')).toBeNull());
    expect(screen.getByText('A terminal application')).toBeTruthy();
  });
  it('prepares a reviewable prompt without starting work, and dismissing does not insert it', async () => {
    read.mockResolvedValue(null);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText("Understand this project's architecture");
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Close analysis settings' }));
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Generate' }));
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledWith(expect.stringContaining('.termdock/architecture.json'), expect.any(HTMLFormElement)));
    expect((await screen.findByRole('status')).textContent).toContain('Review the current input');
  });
  it('browses nested modules, opens source at a verified line, and resets hierarchy when changing perspective', async () => {
    read.mockResolvedValue(document);
    const input = props();
    render(<ArchitecturePanel {...input} />);
    await screen.findByText('A terminal application');
    fireEvent.click(screen.getByRole('button', { name: 'Server' }));
    fireEvent.click(screen.getByRole('button', { name: 'Explore submodules' }));
    fireEvent.click(screen.getByRole('button', { name: 'Routes' }));
    fireEvent.click(screen.getByRole('button', { name: 'src/server/routes/filesystem.ts:50' }));
    expect(input.onOpenFile).toHaveBeenCalledWith({ path: 'src/server/routes/filesystem.ts', line: 50 });
    fireEvent.change(screen.getByRole('combobox', { name: 'Perspective' }), { target: { value: 'data' } });
    expect(screen.getByRole('button', { name: 'Input' })).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Routes' })).toBeNull();
  });
  it('ignores old project results and cancels their request', async () => {
    let resolveOld!: (value: ArchitectureDocument) => void;
    read.mockReturnValueOnce(new Promise(resolve => { resolveOld = resolve; }));
    const input = props();
    const view = render(<ArchitecturePanel {...input} />);
    const signal = read.mock.calls[0][1] as AbortSignal;
    read.mockResolvedValueOnce({ ...document, summary: 'New project' });
    view.rerender(<ArchitecturePanel {...input} rootPath="/new-project" />);
    await screen.findByText('New project');
    expect(signal.aborted).toBe(true);
    await act(async () => resolveOld(document));
    expect(screen.queryByText('A terminal application')).toBeNull();
  });
  it('retains the last valid architecture after an invalid update and recovers on retry', async () => {
    read.mockResolvedValueOnce(document).mockRejectedValueOnce(new ArchitectureFormatError('invalid')).mockResolvedValueOnce({ ...document, summary: 'Updated architecture' });
    render(<ArchitecturePanel {...props()} />);
    await screen.findByText('A terminal application');
    fireEvent.click(screen.getByRole('button', { name: 'Refresh architecture' }));
    await screen.findByRole('alert');
    expect(screen.getByText('A terminal application')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Retry' }));
    await screen.findByText('Updated architecture');
    expect(screen.queryByRole('alert')).toBeNull();
  });
  it('does not load a hidden panel and cancels observation when it becomes hidden', async () => {
    read.mockResolvedValue(null);
    const input = props();
    const view = render(<ArchitecturePanel {...input} active={false} />);
    expect(read).not.toHaveBeenCalled();
    view.rerender(<ArchitecturePanel {...input} />);
    await waitFor(() => expect(read).toHaveBeenCalledOnce());
    const signal = read.mock.calls[0][1] as AbortSignal;
    view.rerender(<ArchitecturePanel {...input} active={false} />);
    expect(signal.aborted).toBe(true);
  });
  it('observes a newly saved architecture without claiming Agent progress', async () => {
    vi.useFakeTimers();
    read.mockResolvedValueOnce(null).mockResolvedValueOnce(document);
    await act(async () => { render(<ArchitecturePanel {...props()} />); });
    expect(screen.getByText("Understand this project's architecture")).toBeTruthy();
    await act(async () => { await vi.advanceTimersByTimeAsync(10_000); });
    expect(screen.getByText('A terminal application')).toBeTruthy();
    expect(read).toHaveBeenCalledTimes(2);
  });
});
