// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ArchitectureGenerationForm } from './ArchitectureGenerationForm';
import { ArchitecturePathPicker } from './ArchitecturePathPicker';
import { FileTree } from './FileTree';
import { useSidebarStore } from '../../stores/useSidebarStore';
import { analysisFile, DEFAULT_ANALYSIS } from '../../architecture/model';
const { list, cancel, search } = vi.hoisted(() => ({ list: vi.fn(), cancel: vi.fn(), search: vi.fn() }));
vi.mock('../../terminal/api', async importOriginal => ({ ...(await importOriginal<typeof import('../../terminal/api')>()), listDirectory: list, cancelIoSlot: cancel, searchFilesStream: search }));
const entries = [{ name: 'src', path: '/project/src', type: 'directory' }, { name: 'auth.ts', path: '/project/auth.ts', type: 'file' }, { name: 'outside', path: '/outside/auth.ts', type: 'file' }];
beforeEach(() => {
  list.mockReset(); cancel.mockReset(); search.mockReset();
  useSidebarStore.setState({ directoryCache: new Map(), expandedPaths: new Set(), fileSortModes: {}, fileSortModesHydrated: true, hideGitIgnoredRoots: {}, hideGitIgnoredRootsHydrated: true, showHiddenFiles: false, gitIgnoreExceptions: {} });
  list.mockImplementation(async (path: string) => ({ path, entries: path === '/project' ? entries : [{ name: 'auth.ts', path: `${path}/auth.ts`, type: 'file' }] }));
  search.mockImplementation(async (_root, _query, onProgress) => onProgress({ done: true, entries: [], total: 0, engine: 'rg' }));
  vi.stubGlobal('IntersectionObserver', class { observe() {} disconnect() {} });
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); });
const props = () => ({ rootPath: '/project', initial: { ...DEFAULT_ANALYSIS, kind: 'feature' as const, target: 'Login retries' }, onInsertPrompt: vi.fn().mockResolvedValue(true), onPrepared: vi.fn(), onClose: vi.fn() });

describe('architecture scope selection', () => {
  it('reuses long-press copying above the chooser without changing the scope', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    vi.stubGlobal('navigator', { clipboard: { writeText } });
    render(<ArchitecturePathPicker rootPath="/project" initial={[]} onCancel={vi.fn()} onConfirm={vi.fn()} />);
    const reference = await screen.findByRole('button', { name: 'Add to analysis scope: auth.ts' });
    vi.useFakeTimers();
    const event = new Event('pointerdown', { bubbles: true, cancelable: true });
    Object.defineProperties(event, { pointerId: { value: 1 }, pointerType: { value: 'touch' }, button: { value: 0 }, clientX: { value: 40 }, clientY: { value: 200 } });
    fireEvent(reference, event);
    await act(async () => { await vi.advanceTimersByTimeAsync(450); });
    const copy = screen.getByRole('button', { name: 'Copy' });
    expect(copy.classList.contains('z-popover')).toBe(true);
    copy.focus(); expect(document.activeElement).toBe(copy);
    fireEvent.click(copy);
    await act(async () => {});
    expect(writeText).toHaveBeenCalledWith('auth.ts');
    expect(reference.getAttribute('aria-pressed')).toBe('false');
    expect(screen.queryByRole('button', { name: 'Remove path: auth.ts' })).toBeNull();
  });
  it('keeps the file-tab and scope-browser request slots independent', async () => {
    render(<><FileTree rootPath="/project" selectedFilePath={null} onFileSelect={vi.fn()} /><ArchitecturePathPicker rootPath="/project" initial={[]} onCancel={vi.fn()} onConfirm={vi.fn()} /></>);
    await screen.findByRole('button', { name: 'Add to analysis scope: auth.ts' });
    const slots = list.mock.calls.filter(call => call[3] === 'load_file_tree_root').map(call => call[4]);
    expect(slots).toContain('file-tree-root:/project');
    expect(slots.some(slot => slot.startsWith('file-tree-reference-root:'))).toBe(true);
    expect(new Set(slots).size).toBe(slots.length);
  });
  it('references the open directory and starts browsing there without changing the feature question', async () => {
    const input = props();
    render(<ArchitectureGenerationForm {...input} currentDirectory="/project/src" currentFile="/project/src/auth.ts" />);
    fireEvent.click(screen.getByRole('button', { name: 'Use current folder' }));
    expect((screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement).value).toBe('src');
    expect((screen.getByRole('button', { name: 'Use current folder' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'Choose folders or files' }));
    await waitFor(() => expect(list).toHaveBeenCalledWith('/project/src', expect.any(AbortSignal), false, 'load_file_tree_root', expect.stringContaining('file-tree-reference-root:'), 'name', expect.any(String)));
    fireEvent.keyDown(document, { key: 'Escape' });
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onPrepared).toHaveBeenCalled());
    expect(input.onPrepared.mock.calls[0][1]).toMatchObject({ target: 'Login retries', paths: ['src'] });
  });
  it('keeps the adjacent browser and question editable together, synchronizes manual scope edits, and protects invalid drafts', async () => {
    vi.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockReturnValue(1200);
    vi.stubGlobal('ResizeObserver', class { observe() {} disconnect() {} });
    list.mockResolvedValue({ entries: [{ name: 'auth.ts', path: '/project/src/auth.ts', type: 'file' }] });
    const input = props();
    render(<ArchitectureGenerationForm {...input} currentDirectory="/project/src" />);
    const browser = screen.getByRole('region', { name: 'Choose folders or files' });
    expect(screen.queryByRole('dialog')).toBeNull();
    fireEvent.click(within(browser).getByRole('button', { name: 'Add to analysis scope: src' }));
    fireEvent.click(await within(browser).findByRole('button', { name: 'Add to analysis scope: auth.ts' }));
    const paths = screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement;
    expect(paths.value).toBe('src\nsrc/auth.ts');
    const filter = within(browser).getByRole('textbox', { name: 'Search files or folders' });
    filter.focus(); expect(document.activeElement).toBe(filter);
    const focus = screen.getByRole('textbox', { name: 'Analysis request and constraints (optional)' });
    focus.focus(); expect(document.activeElement).toBe(focus);
    fireEvent.change(focus, { target: { value: 'Explain cancellation' } });
    fireEvent.change(paths, { target: { value: '/outside/important-draft' } });
    expect((within(browser).getByRole('button', { name: 'Add to analysis scope: auth.ts' }) as HTMLInputElement).disabled).toBe(true);
    fireEvent.click(within(browser).getByRole('button', { name: 'Add to analysis scope: src' }));
    expect(paths.value).toBe('/outside/important-draft');
    fireEvent.change(paths, { target: { value: 'src/auth.ts' } });
    expect(within(browser).getByRole('button', { name: 'Add to analysis scope: auth.ts' }).getAttribute('aria-pressed')).toBe('true');
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onPrepared).toHaveBeenCalled());
    expect(input.onPrepared.mock.calls[0][1]).toMatchObject({ target: 'Login retries', paths: ['src/auth.ts'], focus: 'Explain cancellation' });
  });
  it('preserves a modal draft across widening and keeps the confirmed scope through subsequent responsive switches', async () => {
    let width = 400;
    vi.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockImplementation(() => width);
    let measure!: () => void;
    vi.stubGlobal('ResizeObserver', class { constructor(callback: () => void) { measure = callback; } observe() {} disconnect() {} });
    render(<ArchitectureGenerationForm {...props()} initial={{ ...props().initial, paths: ['auth.ts'] }} />);
    fireEvent.click(screen.getByRole('button', { name: 'Choose folders or files' }));
    fireEvent.click(await screen.findByRole('button', { name: 'Add to analysis scope: src' }));
    act(() => { width = 1200; measure(); });
    expect(screen.getByRole('dialog')).toBeTruthy();
    expect(screen.queryByRole('region', { name: 'Choose folders or files' })).toBeNull();
    fireEvent.keyDown(document, { key: 'Escape' });
    const paths = screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement;
    expect(paths.value).toBe('auth.ts');
    const browser = screen.getByRole('region', { name: 'Choose folders or files' });
    fireEvent.click(await within(browser).findByRole('button', { name: 'Add to analysis scope: src' }));
    act(() => { width = 400; measure(); });
    expect(paths.value).toBe('auth.ts\nsrc');
    expect(screen.queryByRole('region', { name: 'Choose folders or files' })).toBeNull();
    expect(screen.getByRole('button', { name: 'Choose folders or files' })).toBeTruthy();
  });
  it('does not treat another project or the project root as a module directory shortcut', async () => {
    const view = render(<ArchitectureGenerationForm {...props()} currentDirectory="/outside/src" />);
    expect(screen.queryByRole('button', { name: 'Use current folder' })).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: 'Choose folders or files' }));
    await waitFor(() => expect(list).toHaveBeenCalledWith('/project', expect.any(AbortSignal), false, 'load_file_tree_root', expect.stringContaining('file-tree-reference-root:'), 'name', expect.any(String)));
    view.unmount();
    render(<ArchitectureGenerationForm {...props()} currentDirectory="/project" />);
    expect(screen.queryByRole('button', { name: 'Use current folder' })).toBeNull();
  });
  it('adds current-file and copied line references to a feature, deduplicates them, and inserts the complete requested scope', async () => {
    const input = props();
    render(<ArchitectureGenerationForm {...input} currentFile="/project/src/auth.ts" />);
    fireEvent.click(screen.getByRole('button', { name: 'Use current file' }));
    const paths = screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement;
    fireEvent.paste(paths, { clipboardData: { getData: () => '/project/src/auth.ts:12-18\n/project/src/permissions.ts:6' } });
    expect(paths.value).toBe('src/auth.ts\nsrc/permissions.ts');
    fireEvent.change(screen.getByRole('textbox', { name: 'Analysis request and constraints (optional)' }), { target: { value: 'Trace failures and cancellation only' } });
    fireEvent.click(screen.getByRole('button', { name: 'Insert prompt' }));
    await waitFor(() => expect(input.onInsertPrompt).toHaveBeenCalledOnce());
    expect(input.onInsertPrompt.mock.calls[0][0]).toContain('Trace failures and cancellation only');
    const scope = input.onPrepared.mock.calls[0][1];
    expect(scope).toMatchObject({ kind: 'feature', target: 'Login retries', paths: ['src/auth.ts', 'src/permissions.ts'] });
    expect(input.onPrepared.mock.calls[0][0]).toBe(analysisFile(scope));
  });
  it('cancels a picker without changing scope or closing preparation, then commits multiple paths explicitly', async () => {
    const input = props();
    render(<ArchitectureGenerationForm {...input} />);
    fireEvent.click(screen.getByRole('button', { name: 'Choose folders or files' }));
    const first = screen.getByRole('dialog', { name: 'Choose folders or files' });
    fireEvent.click(await within(first).findByRole('button', { name: 'Add to analysis scope: src' }));
    fireEvent.click(within(first).getByRole('button', { name: 'Add to analysis scope: outside' }));
    expect(within(first).queryByRole('button', { name: 'Remove path: outside' })).toBeNull();
    fireEvent.keyDown(document, { key: 'Escape' });
    expect(screen.queryByRole('dialog')).toBeNull();
    expect((screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement).value).toBe('');
    expect(input.onClose).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'Choose folders or files' }));
    const second = screen.getByRole('dialog');
    fireEvent.click(await within(second).findByRole('button', { name: 'Add to analysis scope: src' }));
    fireEvent.click(within(second).getByRole('button', { name: 'Add to analysis scope: auth.ts' }));
    fireEvent.click(within(second).getByRole('button', { name: 'Use selected scope' }));
    expect((screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement).value).toBe('src\nauth.ts');
    expect(input.onInsertPrompt).not.toHaveBeenCalled();
    expect(list).toHaveBeenCalledWith('/project', expect.any(AbortSignal), false, 'load_file_tree_root', expect.stringContaining('file-tree-reference-root:'), 'name', expect.any(String));
  });
  it('keeps the update scope fixed and refuses project-external references without losing the entered draft', () => {
    const input = props();
    const initial = { ...input.initial, paths: ['src'] };
    const component = render(<ArchitectureGenerationForm {...input} initial={initial} outputFile={analysisFile(initial)} currentFile="/outside/auth.ts" />);
    expect(screen.queryByRole('button', { name: 'Choose folders or files' })).toBeNull();
    expect((screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement).readOnly).toBe(true);
    component.unmount();
    render(<ArchitectureGenerationForm {...input} currentFile="/outside/auth.ts" />);
    expect(screen.queryByRole('button', { name: 'Use current file' })).toBeNull();
    fireEvent.change(screen.getByRole('textbox', { name: 'Feature scope (optional)' }), { target: { value: '/outside/auth.ts' } });
    expect((screen.getByRole('button', { name: 'Insert prompt' }) as HTMLButtonElement).disabled).toBe(true);
    expect((screen.getByRole('textbox', { name: 'Feature scope (optional)' }) as HTMLTextAreaElement).value).toBe('/outside/auth.ts');
  });
  it('uses existing expansion and reference controls, searches recursively, and keeps directory-menu Escape in the chooser', async () => {
    const confirm = vi.fn(), cancelPicker = vi.fn();
    render(<ArchitecturePathPicker rootPath="/project" initial={[]} onCancel={cancelPicker} onConfirm={confirm} />);
    const row = await screen.findByTitle('/project/src');
    fireEvent.click(row);
    const child = await screen.findByTitle('/project/src/auth.ts');
    fireEvent.click(within(child).getByRole('button', { name: 'Add to analysis scope: auth.ts' }));
    expect(useSidebarStore.getState().expandedPaths.has('/project/src')).toBe(true);
    expect(screen.queryByRole('button', { name: 'More file actions' })).toBeNull();
    fireEvent.click(within(row).getByRole('button', { name: 'More folder actions' }));
    const enter = screen.getByRole('button', { name: 'Open' });
    enter.focus(); expect(document.activeElement).toBe(enter);
    fireEvent.keyDown(enter, { key: 'Escape' });
    expect(screen.queryByRole('button', { name: 'Open' })).toBeNull();
    expect(cancelPicker).not.toHaveBeenCalled();
    search.mockImplementation(async (_root, _query, progress) => progress({ entries: [{ name: 'deep.ts', path: '/project/src/module/deep.ts', type: 'file' }], done: true, engine: 'rg', total: 1 }));
    fireEvent.change(screen.getByRole('textbox', { name: 'Search files or folders' }), { target: { value: 'deep' } });
    fireEvent.click(await screen.findByRole('button', { name: 'Add to analysis scope: deep.ts' }));
    fireEvent.click(screen.getByRole('button', { name: 'Use selected scope' }));
    expect(confirm).toHaveBeenCalledWith(['src/auth.ts', 'src/module/deep.ts']);
  });
  it('ignores stale directory responses, refreshes failures, and cannot navigate above the project root', async () => {
    let finish!: (value: { entries: typeof entries }) => void;
    list.mockResolvedValueOnce({ entries }).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ entries });
    render(<ArchitecturePathPicker rootPath="/project" initial={[]} onCancel={vi.fn()} onConfirm={vi.fn()} />);
    expect((screen.getByRole('button', { name: 'Parent folder' }) as HTMLButtonElement).disabled).toBe(true);
    const row = await screen.findByTitle('/project/src');
    fireEvent.click(within(row).getByRole('button', { name: 'More folder actions' }));
    fireEvent.click(screen.getByRole('button', { name: 'Open' }));
    await waitFor(() => expect(list).toHaveBeenCalledTimes(2));
    // Returning to the cached root is normally immediate; invalidate it to exercise a real reload failure.
    useSidebarStore.getState().invalidateDirectoryCache('/project', true);
    fireEvent.click(screen.getByRole('button', { name: 'Parent folder' }));
    expect(await screen.findByRole('alert')).toBeTruthy();
    await act(async () => finish({ entries: [{ name: 'stale', path: '/project/src/stale', type: 'file' }] }));
    expect(screen.queryByTitle('/project/src/stale')).toBeNull();
    fireEvent.click(screen.getByRole('button', { name: 'Refresh current folder' }));
    expect(await screen.findByRole('button', { name: 'Add to analysis scope: auth.ts' })).toBeTruthy();
    expect(cancel).toHaveBeenCalled();
  });
});
