#!/usr/bin/env python3
"""Regenerate shipped terminal font shards (requires fonttools[woff]).

The complete fonts remain the editable source and compatibility fallback. Normal
builds use these checked-in, content-addressed shards without requiring Python.
Keep cmap coverage and advance widths exactly equal to the source faces.
"""
from __future__ import annotations

import hashlib
import io
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "public/fonts"
OUTPUT = FONTS / "terminal"


def ranges(points: list[int]) -> str:
    spans: list[list[int]] = []
    for cp in sorted(points):
        if spans and cp == spans[-1][1] + 1:
            spans[-1][1] = cp
        else:
            spans.append([cp, cp])
    return ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in spans)


def main() -> None:
    OUTPUT.mkdir(exist_ok=True)
    css: list[str] = ["/* Generated by scripts/generate-font-subsets.py; do not edit. */"]
    manifest: dict[str, object] = {"schemaVersion": 1, "faces": []}
    expected: set[str] = set()
    for family, stems in [
        ("Termdock Mono", [f"JetBrainsMonoNLNerdFontMono-{w}" for w in ["Regular", "Bold", "Italic", "BoldItalic"]]),
        ("Noto Sans Mono CJK SC", ["NotoSansMonoCJKsc-Subset", "NotoSansMonoCJKsc-Bold-Subset"]),
    ]:
        for stem in stems:
            source = FONTS / f"{stem}.woff2"
            original = TTFont(source)
            cmap = original.getBestCmap()
            groups: dict[str, list[int]] = {}
            for cp in sorted(cmap):
                if family == "Termdock Mono":
                    key = f"icons-{cp // 1024:x}" if 0xE000 <= cp <= 0xF8FF or 0xF0000 <= cp <= 0x10FFFF else "text"
                else:
                    key = f"cjk-{cp // 256:x}" if 0x3400 <= cp <= 0x9FFF else "punctuation"
                groups.setdefault(key, []).append(cp)
            records = []
            for key, points in groups.items():
                font = TTFont(source, recalcTimestamp=False)
                options = subset.Options()
                options.recalc_timestamp = False
                subsetter = subset.Subsetter(options=options)
                subsetter.populate(unicodes=points)
                subsetter.subset(font)
                buffer = io.BytesIO()
                font.save(buffer)
                body = buffer.getvalue()
                name = f"{stem}-{key}-{hashlib.sha256(body).hexdigest()[:12]}.woff2"
                (OUTPUT / name).write_bytes(body)
                expected.add(name)
                # Verify both coverage and metrics rather than trusting the subsetter.
                result = TTFont(io.BytesIO(body))
                result_cmap = result.getBestCmap()
                assert set(result_cmap) == set(points), name
                for cp in points:
                    assert result["hmtx"].metrics[result_cmap[cp]][0] == original["hmtx"].metrics[cmap[cp]][0], (name, cp)
                weight = 700 if "Bold" in stem else 400
                style = "italic" if "Italic" in stem else "normal"
                css.append(f'@font-face{{font-family:"{family}";src:url("/fonts/terminal/{name}") format("woff2");font-weight:{weight};font-style:{style};font-display:swap;unicode-range:{ranges(points)};}}')
                records.append({"file": name, "bytes": len(body), "codepoints": len(points), "group": key})
            manifest["faces"].append({"source": source.name, "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(), "shards": records})
    # Delete only generated font shards; the full source font pack is untouched.
    for old in OUTPUT.glob("*.woff2"):
        if old.name not in expected:
            old.unlink()
    (ROOT / "src/lib/terminal/fontFaces.css").write_text("\n".join(css) + "\n")
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Generated {len(expected)} font shards; coverage and advance widths verified.")


if __name__ == "__main__":
    main()
